version: "2"
services:
  server:
    container_name: "steam-library-server"
    image: "steam-library:0.1"
    working_dir: /home/node/server
    ports:
      - "3042:3042"
    command: >
      /bin/bash -c "npm install
      && npm start"
    volumes:
      - ./server:/home/node/server
    env_file:
      - ./server/.env.prod
  client:
    container_name: "steam-library-client"
    image: "steam-library:0.1"
    working_dir: /home/node/client
    ports:
      - "5142:5142"
    command: >
      /bin/bash -c "npm install
      && npm run build
      && serve -s build -l 5142"
    volumes:
      - ./client:/home/node/client
    env_file:
      - ./client/.env.prod
